trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

variables:
  imageName: 'pipelines-dotnet-core-docker'

steps:
- task: Docker@2
  displayName: Build an image
  inputs:
    repository: $(imageName)
    command: build
    #Dockerfile: app/Dockerfile

- task: Docker@2
  displayName: Login to ACR
  inputs:
    command: login
    containerRegistry: MyAcrConnection

- task: Docker@2
  displayName: Push image to ACR
  inputs:
    command: push
    repository: testrepository
    #dockerfile: $(dockerfilePath)
    #acrUsername: $(ACRUsername)
    #acrUsername: $(ACRUsername)
    #acrUsername: $(ACRUsername)
    containerRegistry: MyAcrConnection
    tags: |
      $(tag)